v: 2024/11/19/001
url: https://ghp.ci/github.com/VonChange/res/archive/refs/heads/master.zip
skipFirst: true
api: http://api.vonchange.com
updateRes: false
apk:
  version: 16
  url: https://ghp.ci/github.com/VonChange/res/archive/refs/heads/master.zip
  force: false
x5Url:
  64:
    - https://tbsall.imtt.qq.com/mtt/release/component/tbs_core_046285_20240613152541_nolog_fs_obfs_arm64-v8a_release.tbs
  32:
    - https://tbs.imtt.qq.com/others/release/x5/tbs_core_046238_20230210164344_nolog_fs_obfs_armeabi_release.tbs
    - https://ghp.ci/github.com/VonChange/utao/releases/download/x5/045738_20210925205342.tbs
data:
  - code: video
    url: video.json
    v: 2024/11/19/001